### ISSUE TITLE
Don't mutate the input options object

### ISSUE THREAD

**Issue by rfk** [mozilla/mysql-patcher#10]
It's fairly likely that users of this lib will pass in their raw MySQL `options` object, so we should avoid mutating it.  In particular, I notice that we set `options.multipleStatements=true` on the input options object and the calling code may not want that.

Since we have a dep on `clone` already, I suggest just cloning the options object up-front and doing our own mutations from there.

**Comment by chilts** [comment]
So #11 supercedes this?

**Comment by rfk** [comment]
Yes, this change is done as part of #11
