### ISSUE TITLE
Ignore dot-files in the patch dir

### ISSUE THREAD

**Issue by rfk** [mozilla/mysql-patcher#15]
If I try to run the patcher while I've got a patch file open in vim, I get this error:

```
Unknown file format: /Users/rfk/repos/mozilla/identity/fxa-auth-db-mysql/db/schema/.patch-008-009.sql.swp
```

It's trying to read the vim swapfile as a patch.  I think we'd be pretty safe to apply unix tradition and ignore filenames that start with a dot.  We could even explicitly filter only that with particular file extensions, in case people want to put e.g. a readme in the patch directory.

**Comment by chilts** [comment]
I think some kind of patch filename format would be the winner and exclude everything else. (This breaks with me with Emacs backup files with names like `*~`.)

At the moment it's doing a `fs.readdir()` which grabs all files in the directory and then checks the filename matches `/-(\d+)-(\d+)\.sql$/`. Instead, perhaps it should just glob on `prefix-*-*.sql` and allow you to specify `prefix` which defaults to `patch`.

**Comment by rfk** [comment]
:thumbsup:

**Comment by chilts** [comment]
PR here : https://github.com/mozilla/mysql-patcher/pull/16

**Comment by chilts** [comment]
Fixed in the PR above.
